### PR TITLE
added language selection when converting to df

### PR DESCRIPTION
**Pull request by Hoohm**
Hello @lgnbhl 

I'm a complete noob with this px format but I managed to tweak the code so that you can select languages when converting a px to a dataframe.

You might be interested in the function as well.
No guarantee, not thoroughly tested.

### CODE REVIEW

**Comment by lgnbhl** [comment]
Hi Patrick,
So so sorry I didn't see your pull request!

**Comment by lgnbhl** [comment]
For some BFS files it seems that the language selection is not working. Any idea how to fix this?

```r
library(BFS) #devtools::install_github("lgnbhl/BFS")
BFS::bfs_download_asset(
  number_bfs = "px-x-1502040100_131",
  destfile = "px-x-1502040100_131.px"
)

data_px <- pxR::read.px(filename = "px-x-1502040100_131.px")
df_fr <- as.data.frame(data_px, language = "fr") #still in German
```

**Comment by Hoohm** [comment]
Haha, this is so old!

To be faire I have no clue. The format is a bit obscure, I tried to read some documentation and figured out how to hack a simple way to solve it for a particular dataset I was interested in.

I can try to actually solve it for more general purposes. Di you have some tests/examples that don't work?

**Comment by lgnbhl** [comment]
Thanks for your feedback!

Actually I am trying to avoid calling `read.px()` in the workflow provided by my package {BFS} (exclusively using the BFS API instead). However, due to API limitation the work around was to download the PXfile and use the `read.px()` function. I hope in the future creating a loop to avoid the API limitation for large data. For reference here the related discussion: https://github.com/lgnbhl/BFS/issues/7#issuecomment-1651593035

So not sure it worth investing time solving this for more general purposes (but it would worth it if there is no way to overcome the API limitation for large data).

**Pull request merged**
